name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the JavaApp Docker Image
      run: 
        docker build /app/Dockerfile -t ${{secrets.DOCKER_USER}}/javaApp:latest -t ${{secrets.DOCKER_USER}}/javaApp:${{ github.sha }} 
      
    - name: Push the JavaApp Docker Image
      run: 
        docker push ${{secrets.DOCKER_USER}}/JavaApp:latest
        docker push ${{secrets.DOCKER_USER}}/JavaApp:${{ github.sha }} 
      
