name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the JavaApp Docker Image
      run: 
        docker build /app/Dockerfile -t ${{secrets.DOCKER_USER}}/javaApp:latest -t ${{secrets.DOCKER_USER}}/javaApp:${{ github.sha }} 
      
    - name: Push the JavaApp Docker Image
      run: 
        docker push ${{secrets.DOCKER_USER}}/JavaApp:latest
        docker push ${{secrets.DOCKER_USER}}/JavaApp:${{ github.sha }} 
      
