name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the JavaApp Docker Image
      run: 
        docker build app/ --tag ${{secrets.DOCKER_USERNAME}}/java_app:latest --tag ${{secrets.DOCKER_USERNAME}}/java_app:${{ github.sha }} 
      
    - name: Push the JavaApp Docker Image
      run: 
        docker push --all-tags ${{secrets.DOCKER_USERNAME}}/java_app
      
    - name: Build the Database Docker Image
      run: 
        docker build database/ --tag ${{secrets.DOCKER_USERNAME}}/database:latest --tag ${{secrets.DOCKER_USERNAME}}/database:${{ github.sha }} 
      
    - name: Push the Database Docker Image
      run: 
        docker push --all-tags ${{secrets.DOCKER_USERNAME}}/database
        
    - name: Build the PaymentGateway Docker Image
      run: 
        docker build payment_gateway/ --tag ${{secrets.DOCKER_USERNAME}}/payment_gateway:latest --tag ${{secrets.DOCKER_USERNAME}}/payment_gateway:${{ github.sha }} 
      
    - name: Push the PaymentGateway Docker Image
      run: 
        docker push --all-tags ${{secrets.DOCKER_USERNAME}}/payment_gateway
        
    - name: Build the ReverseProxy Docker Image
      run: 
        docker build reverse_proxy/ --tag ${{secrets.DOCKER_USERNAME}}/reverse_proxy:latest --tag ${{secrets.DOCKER_USERNAME}}/reverse_proxy:${{ github.sha }} 
      
    - name: Push the ReverseProxy Docker Image
      run: 
        docker push --all-tags ${{secrets.DOCKER_USERNAME}}/reverse_proxy
